//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bkav.eHoadon.XML.xsd
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bkav.eHoadon.XML.xsd.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;xs:schema xmlns=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///    xmlns:inv=&quot;http://laphoadon.gdt.gov.vn/2014/09/invoicexml/v1&quot;
        ///    targetNamespace=&quot;http://laphoadon.gdt.gov.vn/2014/09/invoicexml/v1&quot; elementFormDefault=&quot;qualified&quot;&gt;
        ///
        ///    &lt;complexType name=&quot;error&quot;&gt;
        ///        &lt;xs:all&gt;
        ///            &lt;element name=&quot;code&quot; type=&quot;string&quot;/&gt;
        ///            &lt;element name=&quot;description&quot; type=&quot;string&quot;/&gt;
        ///        &lt;/xs:all&gt;
        ///    &lt;/co [rest of string was truncated]&quot;;.
        /// </summary>
        public static string commons {
            get {
                return ResourceManager.GetString("commons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;xs:schema xmlns=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///    xmlns:inv=&quot;http://laphoadon.gdt.gov.vn/2014/09/invoicexml/v1&quot; targetNamespace=&quot;http://laphoadon.gdt.gov.vn/2014/09/invoicexml/v1&quot;
        ///    elementFormDefault=&quot;qualified&quot;&gt;
        ///
        ///    &lt;xs:include schemaLocation=&quot;commons.xsd&quot;&gt;
        ///        &lt;xs:annotation&gt;
        ///            &lt;xs:documentation&gt;Import of commons.&lt;/xs:documentation&gt;
        ///        &lt;/xs:annotation&gt;
        ///    &lt;/xs:include&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string errors {
            get {
                return ResourceManager.GetString("errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;xs:schema xmlns=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///	xmlns:inv=&quot;http://laphoadon.gdt.gov.vn/2014/09/invoicexml/v1&quot;
        ///	targetNamespace=&quot;http://laphoadon.gdt.gov.vn/2014/09/invoicexml/v1&quot; elementFormDefault=&quot;qualified&quot;
        ///	xmlns:ds=&quot;http://www.w3.org/2000/09/xmldsig#&quot;&gt;
        ///
        ///	&lt;xs:import schemaLocation=&quot;signature.xsd&quot; namespace=&quot;http://www.w3.org/2000/09/xmldsig#&quot;/&gt;
        ///	&lt;xs:include schemaLocation=&quot;commons.xsd&quot;&gt;
        ///		&lt;xs:annotat [rest of string was truncated]&quot;;.
        /// </summary>
        public static string invoice_create {
            get {
                return ResourceManager.GetString("invoice_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;xs:schema xmlns=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///	xmlns:inv=&quot;http://laphoadon.gdt.gov.vn/2014/09/invoicexml/v1&quot;
        ///	targetNamespace=&quot;http://laphoadon.gdt.gov.vn/2014/09/invoicexml/v1&quot; elementFormDefault=&quot;qualified&quot;
        ///	xmlns:ds=&quot;http://www.w3.org/2000/09/xmldsig#&quot;&gt;
        ///
        ///	&lt;xs:import schemaLocation=&quot;signature.xsd&quot; namespace=&quot;http://www.w3.org/2000/09/xmldsig#&quot;/&gt;
        ///	&lt;xs:include schemaLocation=&quot;commons.xsd&quot;&gt;
        ///		&lt;xs:annotat [rest of string was truncated]&quot;;.
        /// </summary>
        public static string invoice_message {
            get {
                return ResourceManager.GetString("invoice_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///   &lt;schema xmlns=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:ds=&quot;http://www.w3.org/2000/09/xmldsig#&quot;
        ///    targetNamespace=&quot;http://www.w3.org/2000/09/xmldsig#&quot; version=&quot;0.1&quot;
        ///    elementFormDefault=&quot;qualified&quot;&gt;
        ///
        ///    &lt;!-- 
        ///    &lt;complexType name=&quot;Signature&quot;&gt;
        ///        &lt;sequence&gt;
        ///            &lt;element name=&quot;SignedInfo&quot; type=&quot;ds:SignedInfo&quot;&gt;&lt;/element&gt;
        ///            &lt;element name=&quot;SignatureValue&quot; type=&quot;string&quot;&gt;&lt;/element&gt;
        ///            &lt;element name=&quot;KeyInfo&quot; type=&quot;ds:KeyInfo&quot;&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string signature {
            get {
                return ResourceManager.GetString("signature", resourceCulture);
            }
        }
    }
}
