//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iHoaDon.Resources.Client {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RegisterModelResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RegisterModelResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iHoaDon.Resources.Client.RegisterModelResource", typeof(RegisterModelResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ (*).
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ không được lớn hơn 500 ký tự!.
        /// </summary>
        public static string AddressMaxLength {
            get {
                return ResourceManager.GetString("AddressMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn phải nhập địa chỉ!.
        /// </summary>
        public static string AddressRequied {
            get {
                return ResourceManager.GetString("AddressRequied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tài khoản (*).
        /// </summary>
        public static string BankAccount {
            get {
                return ResourceManager.GetString("BankAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tài khoản không được lớn hơn 50 ký tự!.
        /// </summary>
        public static string BankAccountMaxLength {
            get {
                return ResourceManager.GetString("BankAccountMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn phải nhập số tài khoản!.
        /// </summary>
        public static string BankAccountRequied {
            get {
                return ResourceManager.GetString("BankAccountRequied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn chữ ký số (*).
        /// </summary>
        public static string CaRequied {
            get {
                return ResourceManager.GetString("CaRequied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã số thuế (mã ngân sách) (*).
        /// </summary>
        public static string CompanyCode {
            get {
                return ResourceManager.GetString("CompanyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã số thuế (mã ngân sách) không được lớn hơn 30  ký tự!.
        /// </summary>
        public static string CompanyCodeMaxLength {
            get {
                return ResourceManager.GetString("CompanyCodeMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn phải nhập mã số thuế (mã ngân sách)!.
        /// </summary>
        public static string CompanyCodeRequied {
            get {
                return ResourceManager.GetString("CompanyCodeRequied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên công ty (*).
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên công ty không được lớn hơn 512  ký tự!.
        /// </summary>
        public static string CompanyNameMaxLength {
            get {
                return ResourceManager.GetString("CompanyNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn phải nhập tên công ty!.
        /// </summary>
        public static string CompanyNameRequied {
            get {
                return ResourceManager.GetString("CompanyNameRequied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận mật khẩu (*).
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu xác nhận không chính xác!.
        /// </summary>
        public static string ConfirmPasswordMustMatch {
            get {
                return ResourceManager.GetString("ConfirmPasswordMustMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo thêm dữ liệu bảng Accounts.
        /// </summary>
        public static string CreateAccounts {
            get {
                return ResourceManager.GetString("CreateAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm dữ liệu bảnh Profile.
        /// </summary>
        public static string CreateProfile {
            get {
                return ResourceManager.GetString("CreateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa dữ liệu bảng Accounts.
        /// </summary>
        public static string DeleteAccounts {
            get {
                return ResourceManager.GetString("DeleteAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa dữ liệu bảng Profile.
        /// </summary>
        public static string DeleteProfile {
            get {
                return ResourceManager.GetString("DeleteProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa dữ liệu bảng Accounts.
        /// </summary>
        public static string EditAccounts {
            get {
                return ResourceManager.GetString("EditAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa dữ liệu bảng Profile.
        /// </summary>
        public static string EditProfile {
            get {
                return ResourceManager.GetString("EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email (*).
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không được lớn hơn 256 ký tự!.
        /// </summary>
        public static string EmailMaxLength {
            get {
                return ResourceManager.GetString("EmailMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn phải nhập Email!.
        /// </summary>
        public static string EmailRequied {
            get {
                return ResourceManager.GetString("EmailRequied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chữ ký số (*).
        /// </summary>
        public static string Issuer {
            get {
                return ResourceManager.GetString("Issuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu (*).
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu tối thiểu phải có 8 ký tự!.
        /// </summary>
        public static string NewPasswordMinLength {
            get {
                return ResourceManager.GetString("NewPasswordMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn phải nhập mật khẩu!.
        /// </summary>
        public static string NewPasswordRequied {
            get {
                return ResourceManager.GetString("NewPasswordRequied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại (*).
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại không được lớn hơn 128 ký tự!.
        /// </summary>
        public static string PhoneMaxLength {
            get {
                return ResourceManager.GetString("PhoneMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn phải nhập số điện thoại!.
        /// </summary>
        public static string PhoneRequied {
            get {
                return ResourceManager.GetString("PhoneRequied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tỉnh thành (*).
        /// </summary>
        public static string Province {
            get {
                return ResourceManager.GetString("Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tỉnh thành  không được lớn hơn 128 ký tự!.
        /// </summary>
        public static string ProvinceMaxLength {
            get {
                return ResourceManager.GetString("ProvinceMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn phải nhập tỉnh thành!.
        /// </summary>
        public static string ProvinceRequied {
            get {
                return ResourceManager.GetString("ProvinceRequied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người đại diện pháp luật .
        /// </summary>
        public static string Representative {
            get {
                return ResourceManager.GetString("Representative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người đại diện pháp luật không được lớn hơn 50 ký tự!.
        /// </summary>
        public static string RepresentativeMaxLength {
            get {
                return ResourceManager.GetString("RepresentativeMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn phải nhập người đại diện pháp luật!.
        /// </summary>
        public static string RepresentativeRequied {
            get {
                return ResourceManager.GetString("RepresentativeRequied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial (*).
        /// </summary>
        public static string Serial {
            get {
                return ResourceManager.GetString("Serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên chữ ký số (*).
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cơ quan thuế quản lý (*).
        /// </summary>
        public static string TaxAgencyCode {
            get {
                return ResourceManager.GetString("TaxAgencyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn phải nhập cơ quan thuế quản lý.
        /// </summary>
        public static string TaxAgencyCodeRequied {
            get {
                return ResourceManager.GetString("TaxAgencyCodeRequied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ ngày (*).
        /// </summary>
        public static string ValidFrom {
            get {
                return ResourceManager.GetString("ValidFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đến ngày (*).
        /// </summary>
        public static string ValidTo {
            get {
                return ResourceManager.GetString("ValidTo", resourceCulture);
            }
        }
    }
}
