//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iHoaDon.Resources.Client {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReissueinvoiceResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReissueinvoiceResource()
        {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iHoaDon.Resources.Client.ReissueinvoiceResource", typeof(ReissueinvoiceResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đến số (*).
        /// </summary>
        public static string EndNumber {
            get {
                return ResourceManager.GetString("EndNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đến số tối đa là 15 ký tự!.
        /// </summary>
        public static string EndNumberMaxLength {
            get {
                return ResourceManager.GetString("EndNumberMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn phải nhập đến số!.
        /// </summary>
        public static string EndNumberRequied {
            get {
                return ResourceManager.GetString("EndNumberRequied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mẫu số (*).
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mẫu số tối đa là 20 ký tự!.
        /// </summary>
        public static string NoMaxLength {
            get {
                return ResourceManager.GetString("NoMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn phải nhập mẫu số!.
        /// </summary>
        public static string NoRequied {
            get {
                return ResourceManager.GetString("NoRequied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng hóa đơn (*).
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng hóa đơn không quá 50 ký tự!.
        /// </summary>
        public static string QuantityMaxLength {
            get {
                return ResourceManager.GetString("QuantityMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn phải nhập số lượng hóa đơn!.
        /// </summary>
        public static string QuantityRequied {
            get {
                return ResourceManager.GetString("QuantityRequied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ký hiệu (*).
        /// </summary>
        public static string SerialInvoice {
            get {
                return ResourceManager.GetString("SerialInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ký hiệu không quá 10 ký  tự!.
        /// </summary>
        public static string SerialInvoiceMaxLength {
            get {
                return ResourceManager.GetString("SerialInvoiceMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn phải nhập ký hiệu!.
        /// </summary>
        public static string SerialInvoiceRequied {
            get {
                return ResourceManager.GetString("SerialInvoiceRequied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ số (*).
        /// </summary>
        public static string StartNumber {
            get {
                return ResourceManager.GetString("StartNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ số tối đa là 15 ký tự!.
        /// </summary>
        public static string StartNumberMaxLength {
            get {
                return ResourceManager.GetString("StartNumberMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn phải nhập từ số!.
        /// </summary>
        public static string StartNumberRequied {
            get {
                return ResourceManager.GetString("StartNumberRequied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày bắt đầu (*).
        /// </summary>
        public static string StartUsingDate {
            get {
                return ResourceManager.GetString("StartUsingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày bắt đầu phải lớn hơn hoặc bằng ngày hiện tại!.
        /// </summary>
        public static string StartUsingDateEqua {
            get {
                return ResourceManager.GetString("StartUsingDateEqua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn phải nhập hoặc chọn ngày bắt đầu!.
        /// </summary>
        public static string StartUsingDateRequied {
            get {
                return ResourceManager.GetString("StartUsingDateRequied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại hóa đơn (*).
        /// </summary>
        public static string TemplateCode {
            get {
                return ResourceManager.GetString("TemplateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn phải chọn loại hóa đơn!.
        /// </summary>
        public static string TemplateCodeRequied {
            get {
                return ResourceManager.GetString("TemplateCodeRequied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã sử dụng đến số (*).
        /// </summary>
        public static string ToNumber {
            get {
                return ResourceManager.GetString("ToNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn phải nhập sử dụng đến số!.
        /// </summary>
        public static string ToNumberRequied {
            get {
                return ResourceManager.GetString("ToNumberRequied", resourceCulture);
            }
        }
    }
}
